Get passengers for Users + Tests PR
ChangePlusPlusVandy/miracleflightsbackend pull request #5
Opened 2024-02-09 16:59 UTC by emrebilge

Not sure if I am doing the testing correctly

2024-02-09 23:39 UTC, begzod03 commented on build/controllers/Passenger.controller.js
> +// Function to get a passenger by their passengerId
Nice comment

2024-02-12 03:43 UTC, jacoblurie29 requested changes

2024-02-12 03:43 UTC, jacoblurie29 commented on package.json
> +    "test": "cross-env ENVIRONMENT=test nyc mocha -r dotenv/config --timeout 20000 --exit -r ts-node/register src/tests/*.tests.ts",
What is this?

2024-02-12 03:43 UTC, jacoblurie29 commented on package.json
> +    "sinon": "^17.0.1",
What is this?

2024-02-12 03:43 UTC, jacoblurie29 commented on package.json
> +    "cross-env": "^7.0.3",
What is this?

2024-02-12 03:43 UTC, jacoblurie29 commented on src/controllers/Passenger.controller.ts
> +  }
Can you comment this out

2024-02-12 03:43 UTC, jacoblurie29 commented on src/tests/PassengerController.tests.ts
> +    airtableBaseStub = sinon.stub(Airtable.prototype, 'base').callsFake(() => ({
what is this

2024-02-13 14:40 UTC, jacoblurie29 approved these changes
LGTM

2024-02-13 14:40 UTC, merged